// Auto-generated mock data seeded from "Tổng hợp báo cáo cv ngày 06.07.xlsx"
export const MOCK_USERS_SEED = [
  {
    "id": "user-1",
    "email": "nguyen.ngoc.tuan@goldenasia.vn",
    "password": "password123",
    "full_name": "Nguyễn Ngọc Tuân",
    "position": "Trưởng nhóm",
    "role": "admin"
  },
  {
    "id": "user-2",
    "email": "duong.hong.hai@goldenasia.vn",
    "password": "password123",
    "full_name": "Dương Hồng Hải",
    "position": "Phó nhóm",
    "role": "user"
  },
  {
    "id": "user-3",
    "email": "nguyen.tran.anh.vu@goldenasia.vn",
    "password": "password123",
    "full_name": "Nguyễn Trần Anh Vũ",
    "position": "Chuyên viên",
    "role": "user"
  },
  {
    "id": "user-4",
    "email": "doan.van.luong@goldenasia.vn",
    "password": "password123",
    "full_name": "Đoàn Văn Lương",
    "position": "Chuyên viên",
    "role": "user"
  },
  {
    "id": "user-5",
    "email": "nguyen.trung.thanh@goldenasia.vn",
    "password": "password123",
    "full_name": "Nguyễn Trung Thành",
    "position": "Chuyên viên",
    "role": "user"
  },
  {
    "id": "user-6",
    "email": "tran.gia.hao@goldenasia.vn",
    "password": "password123",
    "full_name": "Trần Gia Hào",
    "position": "Nhân viên",
    "role": "user"
  },
  {
    "id": "user-7",
    "email": "tran.hoai.nam@goldenasia.vn",
    "password": "password123",
    "full_name": "Trần Hoài Nam",
    "position": "Nhân viên",
    "role": "user"
  },
  {
    "id": "user-8",
    "email": "nguyen.viet.hoang@goldenasia.vn",
    "password": "password123",
    "full_name": "Nguyễn Viết Hoàng",
    "position": "Nhân viên",
    "role": "user"
  },
  {
    "id": "user-9",
    "email": "pham.minh.phuc@goldenasia.vn",
    "password": "password123",
    "full_name": "Phạm Minh Phúc",
    "position": "Nhân viên",
    "role": "user"
  },
  {
    "id": "user-10",
    "email": "ngo.chau.quang.cuong@goldenasia.vn",
    "password": "password123",
    "full_name": "Ngô Châu Quang Cương",
    "position": "Nhân viên",
    "role": "user"
  },
  {
    "id": "user-11",
    "email": "hoang.tien.dat@goldenasia.vn",
    "password": "password123",
    "full_name": "Hoàng Tiến Đạt",
    "position": "Nhân viên",
    "role": "user"
  },
  {
    "id": "user-12",
    "email": "nguyen.truong.vu@goldenasia.vn",
    "password": "password123",
    "full_name": "Nguyễn Trường Vũ",
    "position": "Nhân viên",
    "role": "user"
  },
  {
    "id": "user-13",
    "email": "nguyen.huu.nghia@goldenasia.vn",
    "password": "password123",
    "full_name": "Nguyễn Hữu Nghĩa",
    "position": "Nhân viên",
    "role": "user"
  },
  {
    "id": "user-14",
    "email": "trieu.dinh.viet@goldenasia.vn",
    "password": "password123",
    "full_name": "Triệu Đình Việt",
    "position": "Chuyên viên",
    "role": "user"
  },
  {
    "id": "user-15",
    "email": "le.trong@goldenasia.vn",
    "password": "password123",
    "full_name": "Lê Trọng",
    "position": "Nhân viên",
    "role": "user"
  },
  {
    "id": "user-16",
    "email": "phan.tan.quang@goldenasia.vn",
    "password": "password123",
    "full_name": "Phan Tấn Quang",
    "position": "Nhân viên",
    "role": "user"
  },
  {
    "id": "user-17",
    "email": "nguyen.huu.tai@goldenasia.vn",
    "password": "password123",
    "full_name": "Nguyễn Hữu Tài",
    "position": "Nhân viên",
    "role": "user"
  },
  {
    "id": "user-18",
    "email": "nguyen.ngoc.hau@goldenasia.vn",
    "password": "password123",
    "full_name": "Nguyễn Ngọc Hậu",
    "position": "Nhân viên",
    "role": "user"
  }
];

export const MOCK_REPORTS_SEED = [
  {
    "id": "rep-2",
    "user_id": "user-1",
    "employee_name": "Nguyễn Ngọc Tuân",
    "role_name": "Trưởng nhóm",
    "week": 26,
    "date": "2026-07-06",
    "task_detail": "Tiến độ  DP LCD",
    "plan_locations": 1,
    "plan_screens": 24,
    "plan_details": "UNI: 1/1",
    "actual_locations": 1,
    "actual_screens": 24,
    "actual_details": "UNI: 1/1",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-3",
    "user_id": "user-1",
    "employee_name": "Nguyễn Ngọc Tuân",
    "role_name": "Trưởng nhóm",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Tiến độ GP",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-4",
    "user_id": "user-1",
    "employee_name": "Nguyễn Ngọc Tuân",
    "role_name": "Trưởng nhóm",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Tháo GP",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-5",
    "user_id": "user-1",
    "employee_name": "Nguyễn Ngọc Tuân",
    "role_name": "Trưởng nhóm",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Lắp đặt",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-6",
    "user_id": "user-1",
    "employee_name": "Nguyễn Ngọc Tuân",
    "role_name": "Trưởng nhóm",
    "week": 26,
    "date": "2026-07-06",
    "task_detail": "Quản lý",
    "plan_locations": 1,
    "plan_screens": 1,
    "plan_details": "Sắp xếp công việc\nBrainstorm cùng các host",
    "actual_locations": 1,
    "actual_screens": 1,
    "actual_details": "Sắp xếp công việc\nBrainstorm cùng các host",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-7",
    "user_id": "user-1",
    "employee_name": "Nguyễn Ngọc Tuân",
    "role_name": "Trưởng nhóm",
    "week": 26,
    "date": "2026-07-06",
    "task_detail": "Bảo trì",
    "plan_locations": 1,
    "plan_screens": 1,
    "plan_details": "HL Sarica",
    "actual_locations": 1,
    "actual_screens": 1,
    "actual_details": "HL Sarica",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-8",
    "user_id": "user-1",
    "employee_name": "Nguyễn Ngọc Tuân",
    "role_name": "Trưởng nhóm",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Hỗ trợ",
    "plan_locations": 2,
    "plan_screens": 2,
    "plan_details": "Họp leader\nTham gia training",
    "actual_locations": 2,
    "actual_screens": 2,
    "actual_details": "Họp leader\nTham gia training",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-9",
    "user_id": "user-2",
    "employee_name": "Dương Hồng Hải",
    "role_name": "Phó nhóm",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Tiến độ GP",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-10",
    "user_id": "user-2",
    "employee_name": "Dương Hồng Hải",
    "role_name": "Phó nhóm",
    "week": 26,
    "date": "2026-07-06",
    "task_detail": "Tiến độ  DP LCD",
    "plan_locations": 21,
    "plan_screens": 75,
    "plan_details": "HOTEL : 4\nCF: 9\nFF: 8",
    "actual_locations": 21,
    "actual_screens": 75,
    "actual_details": "HOTEL : 4\nCF: 9\nFF: 8",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-11",
    "user_id": "user-2",
    "employee_name": "Dương Hồng Hải",
    "role_name": "Phó nhóm",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Tháo GP",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-12",
    "user_id": "user-2",
    "employee_name": "Dương Hồng Hải",
    "role_name": "Phó nhóm",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Nghỉ quy định",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-13",
    "user_id": "user-2",
    "employee_name": "Dương Hồng Hải",
    "role_name": "Phó nhóm",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Lắp đặt",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-14",
    "user_id": "user-2",
    "employee_name": "Dương Hồng Hải",
    "role_name": "Phó nhóm",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Làm file",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-15",
    "user_id": "user-2",
    "employee_name": "Dương Hồng Hải",
    "role_name": "Phó nhóm",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Bảo trì",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-16",
    "user_id": "user-3",
    "employee_name": "Nguyễn Trần Anh Vũ",
    "role_name": "Chuyên viên",
    "week": 26,
    "date": "2026-07-06",
    "task_detail": "Tiến độ DP LCD",
    "plan_locations": 3,
    "plan_screens": 128,
    "plan_details": "Toc Vip\nD Edge\nThe Sun Avenue S1-S4",
    "actual_locations": 3,
    "actual_screens": 128,
    "actual_details": "Toc Vip\nD Edge\nThe Sun Avenue S1-S4",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-17",
    "user_id": "user-3",
    "employee_name": "Nguyễn Trần Anh Vũ",
    "role_name": "Chuyên viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Tiến độ GP",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-18",
    "user_id": "user-3",
    "employee_name": "Nguyễn Trần Anh Vũ",
    "role_name": "Chuyên viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Tháo GP",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-19",
    "user_id": "user-3",
    "employee_name": "Nguyễn Trần Anh Vũ",
    "role_name": "Chuyên viên",
    "week": 26,
    "date": "2026-07-06",
    "task_detail": "Lắp đặt",
    "plan_locations": 1,
    "plan_screens": 1,
    "plan_details": "Khảo sát đường điện mới HL 49B Thảo Điền",
    "actual_locations": 1,
    "actual_screens": 1,
    "actual_details": "Khảo sát đường điện mới HL 49B Thảo Điền",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-20",
    "user_id": "user-3",
    "employee_name": "Nguyễn Trần Anh Vũ",
    "role_name": "Chuyên viên",
    "week": 26,
    "date": "2026-07-06",
    "task_detail": "Lắp đặt",
    "plan_locations": 1,
    "plan_screens": 1,
    "plan_details": "HL 2B Lê Duẩn DS2M",
    "actual_locations": 1,
    "actual_screens": 1,
    "actual_details": "HL 2B Lê Duẩn DS2M",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-21",
    "user_id": "user-3",
    "employee_name": "Nguyễn Trần Anh Vũ",
    "role_name": "Chuyên viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Làm file",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-22",
    "user_id": "user-3",
    "employee_name": "Nguyễn Trần Anh Vũ",
    "role_name": "Chuyên viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Hỗ trợ",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-23",
    "user_id": "user-4",
    "employee_name": "Đoàn Văn Lương",
    "role_name": "Chuyên viên",
    "week": 26,
    "date": "2026-07-06",
    "task_detail": "Tiến độ  DP LCD",
    "plan_locations": 2,
    "plan_screens": 8,
    "plan_details": "DH Đồng Nai cs1, 3",
    "actual_locations": 2,
    "actual_screens": 8,
    "actual_details": "DH Đồng Nai cs1, 3",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-24",
    "user_id": "user-4",
    "employee_name": "Đoàn Văn Lương",
    "role_name": "Chuyên viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Tiến độ GP",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-25",
    "user_id": "user-4",
    "employee_name": "Đoàn Văn Lương",
    "role_name": "Chuyên viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Tháo GP",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-26",
    "user_id": "user-4",
    "employee_name": "Đoàn Văn Lương",
    "role_name": "Chuyên viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Lắp đặt",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-27",
    "user_id": "user-4",
    "employee_name": "Đoàn Văn Lương",
    "role_name": "Chuyên viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Bảo trì",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-28",
    "user_id": "user-4",
    "employee_name": "Đoàn Văn Lương",
    "role_name": "Chuyên viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Làm file",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-29",
    "user_id": "user-4",
    "employee_name": "Đoàn Văn Lương",
    "role_name": "Chuyên viên",
    "week": 26,
    "date": "2026-07-06",
    "task_detail": "Hỗ trợ",
    "plan_locations": 2,
    "plan_screens": 2,
    "plan_details": "Chia GP\nTham gia Training",
    "actual_locations": 2,
    "actual_screens": 2,
    "actual_details": "Chia GP\nTham gia Training",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-30",
    "user_id": "user-5",
    "employee_name": "Nguyễn Trung Thành",
    "role_name": "Chuyên viên",
    "week": 26,
    "date": "2026-07-06",
    "task_detail": "Tiến độ  DP LCD",
    "plan_locations": 6,
    "plan_screens": 51,
    "plan_details": "HOTEL: 2\nFF: 4",
    "actual_locations": 6,
    "actual_screens": 51,
    "actual_details": "HOTEL: 2\nFF: 4",
    "progress_eval": "Hoàn thành",
    "notes": "Công tác Phan Thiết"
  },
  {
    "id": "rep-31",
    "user_id": "user-5",
    "employee_name": "Nguyễn Trung Thành",
    "role_name": "Chuyên viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Tiến độ GP",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-32",
    "user_id": "user-5",
    "employee_name": "Nguyễn Trung Thành",
    "role_name": "Chuyên viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Tháo GP",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-33",
    "user_id": "user-5",
    "employee_name": "Nguyễn Trung Thành",
    "role_name": "Chuyên viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Lắp đặt",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-34",
    "user_id": "user-5",
    "employee_name": "Nguyễn Trung Thành",
    "role_name": "Chuyên viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Bảo trì",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-35",
    "user_id": "user-5",
    "employee_name": "Nguyễn Trung Thành",
    "role_name": "Chuyên viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Làm file",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-36",
    "user_id": "user-5",
    "employee_name": "Nguyễn Trung Thành",
    "role_name": "Chuyên viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Hỗ trợ",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-37",
    "user_id": "user-6",
    "employee_name": "Trần Gia Hào",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-06",
    "task_detail": "Tiến độ  DP LCD",
    "plan_locations": 2,
    "plan_screens": 62,
    "plan_details": "Building : 2/2",
    "actual_locations": 2,
    "actual_screens": 62,
    "actual_details": "Building : 2/2",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-38",
    "user_id": "user-6",
    "employee_name": "Trần Gia Hào",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Tiến độ GP",
    "plan_locations": 0,
    "plan_screens": 0,
    "plan_details": "",
    "actual_locations": 0,
    "actual_screens": 0,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-39",
    "user_id": "user-6",
    "employee_name": "Trần Gia Hào",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Tháo GP",
    "plan_locations": 0,
    "plan_screens": 0,
    "plan_details": "",
    "actual_locations": 0,
    "actual_screens": 0,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-40",
    "user_id": "user-6",
    "employee_name": "Trần Gia Hào",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-06",
    "task_detail": "Bảo trì",
    "plan_locations": 1,
    "plan_screens": 1,
    "plan_details": "Thay dây và CB KTX ĐH Saigon mất nguồn cabin",
    "actual_locations": 1,
    "actual_screens": 1,
    "actual_details": "Thay dây và CB KTX ĐH Saigon mất nguồn cabin",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-41",
    "user_id": "user-6",
    "employee_name": "Trần Gia Hào",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Làm file",
    "plan_locations": 0,
    "plan_screens": 0,
    "plan_details": "",
    "actual_locations": 0,
    "actual_screens": 0,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-42",
    "user_id": "user-6",
    "employee_name": "Trần Gia Hào",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-06",
    "task_detail": "Hỗ trợ",
    "plan_locations": 2,
    "plan_screens": 2,
    "plan_details": "- Soan chia GP\n- Tham gia Present",
    "actual_locations": 2,
    "actual_screens": 2,
    "actual_details": "- Soan chia GP\n- Tham gia Present",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-43",
    "user_id": "user-7",
    "employee_name": "Trần Hoài Nam",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Tiến độ  DP LCD",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-44",
    "user_id": "user-7",
    "employee_name": "Trần Hoài Nam",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-06",
    "task_detail": "Tiến độ GP",
    "plan_locations": 4,
    "plan_screens": 4,
    "plan_details": "Công nghiệp, An Lộc, Hà Đô river side",
    "actual_locations": 4,
    "actual_screens": 4,
    "actual_details": "Công nghiệp, An Lộc, Hà Đô river side",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-45",
    "user_id": "user-7",
    "employee_name": "Trần Hoài Nam",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Tháo GP",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-46",
    "user_id": "user-7",
    "employee_name": "Trần Hoài Nam",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Lắp đặt",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-47",
    "user_id": "user-7",
    "employee_name": "Trần Hoài Nam",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Lắp đặt",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-48",
    "user_id": "user-7",
    "employee_name": "Trần Hoài Nam",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Làm file",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-49",
    "user_id": "user-7",
    "employee_name": "Trần Hoài Nam",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-06",
    "task_detail": "Hỗ trợ",
    "plan_locations": 1,
    "plan_screens": 1,
    "plan_details": "Bật màn CD Viễn Đông",
    "actual_locations": 1,
    "actual_screens": 1,
    "actual_details": "Bật on màn CD Viễn Đông",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-50",
    "user_id": "user-8",
    "employee_name": "Nguyễn Viết Hoàng",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-06",
    "task_detail": "Tiến độ  DP LCD",
    "plan_locations": 1,
    "plan_screens": 25,
    "plan_details": "BUILDING : 1/1",
    "actual_locations": 1,
    "actual_screens": 25,
    "actual_details": "BUILDING : 1/1",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-51",
    "user_id": "user-8",
    "employee_name": "Nguyễn Viết Hoàng",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Tiến độ GP",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-52",
    "user_id": "user-8",
    "employee_name": "Nguyễn Viết Hoàng",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Tháo GP",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-53",
    "user_id": "user-8",
    "employee_name": "Nguyễn Viết Hoàng",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-06",
    "task_detail": "Lắp đặt",
    "plan_locations": 1,
    "plan_screens": 2,
    "plan_details": "Thu hồi DS chung cư Cove",
    "actual_locations": 1,
    "actual_screens": 2,
    "actual_details": "Thu hồi DS chung cư Cove",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-54",
    "user_id": "user-8",
    "employee_name": "Nguyễn Viết Hoàng",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Bảo trì",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-55",
    "user_id": "user-8",
    "employee_name": "Nguyễn Viết Hoàng",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Làm file",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-56",
    "user_id": "user-8",
    "employee_name": "Nguyễn Viết Hoàng",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-06",
    "task_detail": "Hỗ trợ",
    "plan_locations": 1,
    "plan_screens": 2,
    "plan_details": "Soạn GP\nNghe Present",
    "actual_locations": 1,
    "actual_screens": 2,
    "actual_details": "Soạn GP\nNghe Present",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-57",
    "user_id": "user-9",
    "employee_name": "Phạm Minh Phúc",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Tiến độ  DP LCD",
    "plan_locations": 25,
    "plan_screens": 92,
    "plan_details": "Công tac Vũng Tàu",
    "actual_locations": 25,
    "actual_screens": 92,
    "actual_details": "Công tac Vũng Tàu",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-58",
    "user_id": "user-9",
    "employee_name": "Phạm Minh Phúc",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Tiến độ GP",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-59",
    "user_id": "user-9",
    "employee_name": "Phạm Minh Phúc",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Tháo GP",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-60",
    "user_id": "user-9",
    "employee_name": "Phạm Minh Phúc",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Lắp đặt",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-61",
    "user_id": "user-9",
    "employee_name": "Phạm Minh Phúc",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Bảo trì",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-62",
    "user_id": "user-9",
    "employee_name": "Phạm Minh Phúc",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Làm file",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-63",
    "user_id": "user-9",
    "employee_name": "Phạm Minh Phúc",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Nghỉ quy định",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-64",
    "user_id": "user-10",
    "employee_name": "Ngô Châu Quang Cương",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-06",
    "task_detail": "Tiến độ  DP LCD",
    "plan_locations": 2,
    "plan_screens": 68,
    "plan_details": "UNI : 1/1\n\n+ BUILDING: 1/1",
    "actual_locations": 2,
    "actual_screens": 68,
    "actual_details": "UNI : 1/1\n\n+ BUILDING: 1/1",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-65",
    "user_id": "user-10",
    "employee_name": "Ngô Châu Quang Cương",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Tiến độ GP",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-66",
    "user_id": "user-10",
    "employee_name": "Ngô Châu Quang Cương",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Tháo GP",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-67",
    "user_id": "user-10",
    "employee_name": "Ngô Châu Quang Cương",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-06",
    "task_detail": "Lắp đặt",
    "plan_locations": 1,
    "plan_screens": 3,
    "plan_details": "Thu hồi HL 331 Lê Văn Việt",
    "actual_locations": 1,
    "actual_screens": 3,
    "actual_details": "Thu hồi HL 331 Lê Văn Việt",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-68",
    "user_id": "user-10",
    "employee_name": "Ngô Châu Quang Cương",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Bảo trì",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-69",
    "user_id": "user-10",
    "employee_name": "Ngô Châu Quang Cương",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Làm file",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-70",
    "user_id": "user-10",
    "employee_name": "Ngô Châu Quang Cương",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-06",
    "task_detail": "Hỗ trợ",
    "plan_locations": 2,
    "plan_screens": 2,
    "plan_details": "Nghe Sếp Truyền cảm hứng. Nhận và chia GP",
    "actual_locations": 2,
    "actual_screens": 2,
    "actual_details": "Nghe Sếp Truyền cảm hứng. Nhận và chia GP",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-71",
    "user_id": "user-11",
    "employee_name": "Hoàng Tiến Đạt",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-06",
    "task_detail": "Nghỉ dài hạn",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "Nghỉ dài hạn",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "Nghỉ dài hạn",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-72",
    "user_id": "user-11",
    "employee_name": "Hoàng Tiến Đạt",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Tiến độ GP",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-73",
    "user_id": "user-11",
    "employee_name": "Hoàng Tiến Đạt",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Tháo GP",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-74",
    "user_id": "user-11",
    "employee_name": "Hoàng Tiến Đạt",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Lắp đặt",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-75",
    "user_id": "user-11",
    "employee_name": "Hoàng Tiến Đạt",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Bảo trì",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-76",
    "user_id": "user-11",
    "employee_name": "Hoàng Tiến Đạt",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Làm file",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-77",
    "user_id": "user-11",
    "employee_name": "Hoàng Tiến Đạt",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Hỗ trợ",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-78",
    "user_id": "user-12",
    "employee_name": "Nguyễn Trường Vũ",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-06",
    "task_detail": "Tiến độ  DP LCD",
    "plan_locations": 39,
    "plan_screens": 110,
    "plan_details": "+ UNI: 4/4\n+ CF : 15/15\n+ FF: 10/10\n+ SL : 10/10",
    "actual_locations": 39,
    "actual_screens": 110,
    "actual_details": "+ UNI: 4/4\n+ CF : 15/15\n+ FF: 10/10\n+ SL : 10/10",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-79",
    "user_id": "user-12",
    "employee_name": "Nguyễn Trường Vũ",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Tiến độ GP",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-80",
    "user_id": "user-12",
    "employee_name": "Nguyễn Trường Vũ",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Tháo GP",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-81",
    "user_id": "user-12",
    "employee_name": "Nguyễn Trường Vũ",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Lắp đặt",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-82",
    "user_id": "user-12",
    "employee_name": "Nguyễn Trường Vũ",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Bảo trì",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-83",
    "user_id": "user-12",
    "employee_name": "Nguyễn Trường Vũ",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Làm file",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-84",
    "user_id": "user-12",
    "employee_name": "Nguyễn Trường Vũ",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Hỗ trợ",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-85",
    "user_id": "user-13",
    "employee_name": "Nguyễn Hữu Nghĩa",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-06",
    "task_detail": "Tiến độ  DP LCD",
    "plan_locations": 1,
    "plan_screens": 74,
    "plan_details": "Building: 1/1",
    "actual_locations": 1,
    "actual_screens": 74,
    "actual_details": "Building: 1/1",
    "progress_eval": "Hoàn thành",
    "notes": "The Sun Avenua S5 tới S8"
  },
  {
    "id": "rep-86",
    "user_id": "user-13",
    "employee_name": "Nguyễn Hữu Nghĩa",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Tiến độ GP",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-87",
    "user_id": "user-13",
    "employee_name": "Nguyễn Hữu Nghĩa",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Tháo GP",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-88",
    "user_id": "user-13",
    "employee_name": "Nguyễn Hữu Nghĩa",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Lắp đặt",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-89",
    "user_id": "user-13",
    "employee_name": "Nguyễn Hữu Nghĩa",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Bảo trì",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-90",
    "user_id": "user-13",
    "employee_name": "Nguyễn Hữu Nghĩa",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Làm file",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-91",
    "user_id": "user-13",
    "employee_name": "Nguyễn Hữu Nghĩa",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-06",
    "task_detail": "Hỗ trợ",
    "plan_locations": 1,
    "plan_screens": 2,
    "plan_details": "Soạn GP\nNghe Present",
    "actual_locations": 1,
    "actual_screens": 2,
    "actual_details": "Soạn GP\nNghe Present",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-92",
    "user_id": "user-14",
    "employee_name": "Triệu Đình Việt",
    "role_name": "Chuyên viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Tiến độ  DP LCD",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-93",
    "user_id": "user-14",
    "employee_name": "Triệu Đình Việt",
    "role_name": "Chuyên viên",
    "week": 26,
    "date": "2026-07-06",
    "task_detail": "Tiến độ GP",
    "plan_locations": 2,
    "plan_screens": 3,
    "plan_details": "CC F-home, CC Bluehouse",
    "actual_locations": 2,
    "actual_screens": 3,
    "actual_details": "CC F-home, CC Bluehouse",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-94",
    "user_id": "user-14",
    "employee_name": "Triệu Đình Việt",
    "role_name": "Chuyên viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Tháo GP",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-95",
    "user_id": "user-14",
    "employee_name": "Triệu Đình Việt",
    "role_name": "Chuyên viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Lắp đặt",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-96",
    "user_id": "user-14",
    "employee_name": "Triệu Đình Việt",
    "role_name": "Chuyên viên",
    "week": 26,
    "date": "2026-07-06",
    "task_detail": "Bảo trì",
    "plan_locations": 1,
    "plan_screens": 1,
    "plan_details": "Hottel Samarino",
    "actual_locations": 1,
    "actual_screens": 1,
    "actual_details": "Hottel Samarino",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-97",
    "user_id": "user-14",
    "employee_name": "Triệu Đình Việt",
    "role_name": "Chuyên viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Làm file",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-98",
    "user_id": "user-14",
    "employee_name": "Triệu Đình Việt",
    "role_name": "Chuyên viên",
    "week": 26,
    "date": "2026-07-06",
    "task_detail": "Hỗ trợ",
    "plan_locations": 1,
    "plan_screens": 1,
    "plan_details": "Tham gia training",
    "actual_locations": 1,
    "actual_screens": 1,
    "actual_details": "Tham gia training",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-99",
    "user_id": "user-15",
    "employee_name": "Lê Trọng",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-06",
    "task_detail": "Tiến độ  DP LCD",
    "plan_locations": 1,
    "plan_screens": 9,
    "plan_details": "Trường CĐ KTKH",
    "actual_locations": 1,
    "actual_screens": 9,
    "actual_details": "Trường CĐ KTKH",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-100",
    "user_id": "user-15",
    "employee_name": "Lê Trọng",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Tiến độ GP",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-101",
    "user_id": "user-15",
    "employee_name": "Lê Trọng",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Tháo GP",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-102",
    "user_id": "user-15",
    "employee_name": "Lê Trọng",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Lắp đặt",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-103",
    "user_id": "user-15",
    "employee_name": "Lê Trọng",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Bảo trì",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-104",
    "user_id": "user-15",
    "employee_name": "Lê Trọng",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Làm file",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-105",
    "user_id": "user-15",
    "employee_name": "Lê Trọng",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-06",
    "task_detail": "Hỗ trợ",
    "plan_locations": 5,
    "plan_screens": 38,
    "plan_details": "Chạy chương trình tuyến Hội An gồm 3 Hotel , 1 lotteria , 1 Phúc Long",
    "actual_locations": 5,
    "actual_screens": 36,
    "actual_details": "Chạy chương trình tuyến Hội An gồm 3 Hotel , 1 lotteria , 1 Phúc Long",
    "progress_eval": "Hoàn thành",
    "notes": "Koi Resort & Spa ngắt nguồn màn hình"
  },
  {
    "id": "rep-106",
    "user_id": "user-16",
    "employee_name": "Phan Tấn Quang",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-06",
    "task_detail": "Tiến độ  DP LCD",
    "plan_locations": 33,
    "plan_screens": 144,
    "plan_details": "+ UNI : 3/3\n+ CF : 11/11\n+ FF : 3/3\n+ SL : 8/8\n+ Hotel: 7/7",
    "actual_locations": 33,
    "actual_screens": 144,
    "actual_details": "+ UNI : 3/3\n+ CF : 11/11\n+ FF : 3/3\n+ SL : 8/8\n+ Hotel: 7/7",
    "progress_eval": "Hoàn thành",
    "notes": "+ UNI : 3/3\n+ CF : 11/11\n+ FF : 3/3\n+ SL : 8/8\n+ Hotel: 7/7"
  },
  {
    "id": "rep-107",
    "user_id": "user-16",
    "employee_name": "Phan Tấn Quang",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Tiến độ GP",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-108",
    "user_id": "user-16",
    "employee_name": "Phan Tấn Quang",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Tháo GP",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-109",
    "user_id": "user-16",
    "employee_name": "Phan Tấn Quang",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Lắp đặt",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-110",
    "user_id": "user-16",
    "employee_name": "Phan Tấn Quang",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Bảo trì",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-111",
    "user_id": "user-16",
    "employee_name": "Phan Tấn Quang",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Làm file",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-112",
    "user_id": "user-16",
    "employee_name": "Phan Tấn Quang",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-06",
    "task_detail": "Hỗ trợ",
    "plan_locations": 2,
    "plan_screens": 2,
    "plan_details": "- Tham gia Present Founder\n- Brainstorm",
    "actual_locations": 2,
    "actual_screens": 2,
    "actual_details": "- Tham gia Present Founder\n- Brainstorm",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-113",
    "user_id": "user-17",
    "employee_name": "Nguyễn Hữu Tài",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Tiến độ  DP LCD",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-114",
    "user_id": "user-17",
    "employee_name": "Nguyễn Hữu Tài",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Tiến độ GP",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-115",
    "user_id": "user-17",
    "employee_name": "Nguyễn Hữu Tài",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Tháo GP",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-116",
    "user_id": "user-17",
    "employee_name": "Nguyễn Hữu Tài",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Lắp đặt",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-117",
    "user_id": "user-17",
    "employee_name": "Nguyễn Hữu Tài",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Bảo trì",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-118",
    "user_id": "user-17",
    "employee_name": "Nguyễn Hữu Tài",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Làm file",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-119",
    "user_id": "user-17",
    "employee_name": "Nguyễn Hữu Tài",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "R&D",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-120",
    "user_id": "user-18",
    "employee_name": "Nguyễn Ngọc Hậu",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-06",
    "task_detail": "Tiến độ  DP LCD",
    "plan_locations": 6,
    "plan_screens": 89,
    "plan_details": "HOTEL: 6",
    "actual_locations": 6,
    "actual_screens": 89,
    "actual_details": "HOTEL: 6",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-121",
    "user_id": "user-18",
    "employee_name": "Nguyễn Ngọc Hậu",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Tiến độ GP",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-122",
    "user_id": "user-18",
    "employee_name": "Nguyễn Ngọc Hậu",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Tháo GP",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-123",
    "user_id": "user-18",
    "employee_name": "Nguyễn Ngọc Hậu",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Lắp đặt",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-124",
    "user_id": "user-18",
    "employee_name": "Nguyễn Ngọc Hậu",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Bảo trì",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-125",
    "user_id": "user-18",
    "employee_name": "Nguyễn Ngọc Hậu",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Làm file",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  },
  {
    "id": "rep-126",
    "user_id": "user-18",
    "employee_name": "Nguyễn Ngọc Hậu",
    "role_name": "Nhân viên",
    "week": 26,
    "date": "2026-07-04",
    "task_detail": "Hỗ trợ",
    "plan_locations": null,
    "plan_screens": null,
    "plan_details": "",
    "actual_locations": null,
    "actual_screens": null,
    "actual_details": "",
    "progress_eval": "Hoàn thành",
    "notes": ""
  }
];
